import type { Migration } from './types';

export const migration002: Migration = {
  version: 2,
  name: 'create-content-schema',
  kind: 'structure',
  statements: [
    `CREATE TABLE content_versions (
      content_version TEXT PRIMARY KEY CHECK (length(content_version) > 0 AND content_version <> 'latest'),
      schema_version TEXT NOT NULL CHECK (length(schema_version) > 0 AND schema_version <> 'latest'),
      status TEXT NOT NULL CHECK (status IN ('draft', 'verified')),
      completeness_mode TEXT NOT NULL CHECK (completeness_mode IN ('partial', 'complete')),
      source_file TEXT NOT NULL,
      payload_hash TEXT NOT NULL,
      record_count INTEGER NOT NULL CHECK (record_count >= 0),
      created_at TEXT NOT NULL,
      imported_at TEXT NOT NULL,
      notes TEXT NOT NULL
    )`,
    `CREATE TABLE data_sources (
      source_id TEXT NOT NULL,
      source_version TEXT NOT NULL CHECK (source_version <> 'latest'),
      title TEXT NOT NULL CHECK (length(title) > 0),
      edition TEXT,
      locator TEXT,
      source_type TEXT NOT NULL CHECK (source_type IN ('classical-text', 'modern-study', 'authorized-dataset', 'internal-derivation', 'pending')),
      license_status TEXT NOT NULL CHECK (license_status IN ('cleared', 'public-domain', 'restricted', 'pending')),
      status TEXT NOT NULL CHECK (status IN ('draft', 'verified')),
      verified_by TEXT,
      verified_at TEXT,
      notes TEXT NOT NULL,
      metadata_hash TEXT NOT NULL,
      PRIMARY KEY (source_id, source_version),
      CHECK (status <> 'verified' OR (verified_by IS NOT NULL AND verified_at IS NOT NULL AND source_type <> 'pending' AND license_status <> 'pending'))
    )`,
    `CREATE TABLE rule_versions (
      ruleset_id TEXT NOT NULL,
      ruleset_version TEXT NOT NULL CHECK (ruleset_version <> 'latest'),
      content_version TEXT NOT NULL,
      system_name TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('draft', 'verified', 'retired')),
      scope TEXT NOT NULL,
      verified_by TEXT,
      verified_at TEXT,
      notes TEXT NOT NULL,
      PRIMARY KEY (ruleset_id, ruleset_version),
      FOREIGN KEY (content_version) REFERENCES content_versions(content_version) ON DELETE RESTRICT,
      CHECK (status <> 'verified' OR (verified_by IS NOT NULL AND verified_at IS NOT NULL))
    )`,
    `CREATE TABLE rule_version_sources (
      ruleset_id TEXT NOT NULL,
      ruleset_version TEXT NOT NULL,
      source_id TEXT NOT NULL,
      source_version TEXT NOT NULL,
      PRIMARY KEY (ruleset_id, ruleset_version, source_id, source_version),
      FOREIGN KEY (ruleset_id, ruleset_version) REFERENCES rule_versions(ruleset_id, ruleset_version) ON DELETE RESTRICT,
      FOREIGN KEY (source_id, source_version) REFERENCES data_sources(source_id, source_version) ON DELETE RESTRICT
    )`,
    `CREATE TABLE trigrams (
      trigram_id TEXT NOT NULL,
      content_version TEXT NOT NULL,
      source_id TEXT NOT NULL,
      source_version TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('draft', 'verified')),
      name TEXT NOT NULL,
      symbol TEXT NOT NULL,
      code TEXT NOT NULL CHECK (length(code) = 3 AND code NOT GLOB '*[^01]*'),
      line_1 INTEGER NOT NULL CHECK (line_1 IN (0, 1)),
      line_2 INTEGER NOT NULL CHECK (line_2 IN (0, 1)),
      line_3 INTEGER NOT NULL CHECK (line_3 IN (0, 1)),
      classical_text TEXT,
      modern_text TEXT,
      PRIMARY KEY (trigram_id, content_version),
      UNIQUE (content_version, code),
      FOREIGN KEY (content_version) REFERENCES content_versions(content_version) ON DELETE RESTRICT,
      FOREIGN KEY (source_id, source_version) REFERENCES data_sources(source_id, source_version) ON DELETE RESTRICT
    )`,
    `CREATE TABLE hexagrams (
      hexagram_id TEXT NOT NULL,
      content_version TEXT NOT NULL,
      source_id TEXT NOT NULL,
      source_version TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('draft', 'verified')),
      king_wen_sequence INTEGER NOT NULL CHECK (king_wen_sequence BETWEEN 1 AND 64),
      name TEXT NOT NULL,
      upper_trigram_id TEXT NOT NULL,
      lower_trigram_id TEXT NOT NULL,
      code TEXT NOT NULL CHECK (length(code) = 6 AND code NOT GLOB '*[^01]*'),
      classical_text TEXT,
      modern_text TEXT,
      PRIMARY KEY (hexagram_id, content_version),
      UNIQUE (content_version, king_wen_sequence),
      UNIQUE (content_version, upper_trigram_id, lower_trigram_id),
      UNIQUE (content_version, code),
      FOREIGN KEY (content_version) REFERENCES content_versions(content_version) ON DELETE RESTRICT,
      FOREIGN KEY (upper_trigram_id, content_version) REFERENCES trigrams(trigram_id, content_version) ON DELETE RESTRICT,
      FOREIGN KEY (lower_trigram_id, content_version) REFERENCES trigrams(trigram_id, content_version) ON DELETE RESTRICT,
      FOREIGN KEY (source_id, source_version) REFERENCES data_sources(source_id, source_version) ON DELETE RESTRICT
    )`,
    `CREATE TABLE hexagram_lines (
      line_id TEXT NOT NULL,
      hexagram_id TEXT NOT NULL,
      line_position INTEGER NOT NULL CHECK (line_position BETWEEN 1 AND 6),
      content_version TEXT NOT NULL,
      source_id TEXT NOT NULL,
      source_version TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('draft', 'verified')),
      classical_text TEXT,
      modern_text TEXT,
      PRIMARY KEY (line_id, content_version),
      UNIQUE (hexagram_id, line_position, content_version),
      FOREIGN KEY (hexagram_id, content_version) REFERENCES hexagrams(hexagram_id, content_version) ON DELETE RESTRICT,
      FOREIGN KEY (source_id, source_version) REFERENCES data_sources(source_id, source_version) ON DELETE RESTRICT
    )`,
    `CREATE TABLE special_line_texts (
      special_line_id TEXT NOT NULL,
      hexagram_id TEXT NOT NULL,
      kind TEXT NOT NULL CHECK (kind IN ('use-nine', 'use-six')),
      content_version TEXT NOT NULL,
      source_id TEXT NOT NULL,
      source_version TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('draft', 'verified')),
      classical_text TEXT,
      modern_text TEXT,
      PRIMARY KEY (special_line_id, content_version),
      UNIQUE (kind, content_version),
      FOREIGN KEY (hexagram_id, content_version) REFERENCES hexagrams(hexagram_id, content_version) ON DELETE RESTRICT,
      FOREIGN KEY (source_id, source_version) REFERENCES data_sources(source_id, source_version) ON DELETE RESTRICT
    )`,
    `CREATE TABLE palace_hexagrams (
      palace_hexagram_id TEXT NOT NULL,
      content_version TEXT NOT NULL,
      source_id TEXT NOT NULL,
      source_version TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('draft', 'verified')),
      ruleset_id TEXT NOT NULL,
      ruleset_version TEXT NOT NULL,
      palace_trigram_id TEXT NOT NULL,
      hexagram_id TEXT NOT NULL,
      palace_position INTEGER NOT NULL CHECK (palace_position BETWEEN 1 AND 8),
      shi_position INTEGER NOT NULL CHECK (shi_position BETWEEN 1 AND 6),
      ying_position INTEGER NOT NULL CHECK (ying_position BETWEEN 1 AND 6),
      PRIMARY KEY (palace_hexagram_id, content_version),
      UNIQUE (ruleset_id, ruleset_version, hexagram_id),
      UNIQUE (ruleset_id, ruleset_version, palace_trigram_id, palace_position),
      FOREIGN KEY (ruleset_id, ruleset_version) REFERENCES rule_versions(ruleset_id, ruleset_version) ON DELETE RESTRICT,
      FOREIGN KEY (palace_trigram_id, content_version) REFERENCES trigrams(trigram_id, content_version) ON DELETE RESTRICT,
      FOREIGN KEY (hexagram_id, content_version) REFERENCES hexagrams(hexagram_id, content_version) ON DELETE RESTRICT,
      FOREIGN KEY (source_id, source_version) REFERENCES data_sources(source_id, source_version) ON DELETE RESTRICT,
      CHECK (shi_position <> ying_position)
    )`,
    `CREATE TABLE najia_assignments (
      najia_assignment_id TEXT NOT NULL,
      content_version TEXT NOT NULL,
      source_id TEXT NOT NULL,
      source_version TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('draft', 'verified')),
      ruleset_id TEXT NOT NULL,
      ruleset_version TEXT NOT NULL,
      trigram_id TEXT NOT NULL,
      polarity TEXT NOT NULL CHECK (polarity IN ('yin', 'yang')),
      line_position INTEGER NOT NULL CHECK (line_position BETWEEN 1 AND 3),
      heavenly_stem_id TEXT NOT NULL,
      earthly_branch_id TEXT NOT NULL,
      PRIMARY KEY (najia_assignment_id, content_version),
      UNIQUE (ruleset_id, ruleset_version, trigram_id, polarity, line_position),
      FOREIGN KEY (ruleset_id, ruleset_version) REFERENCES rule_versions(ruleset_id, ruleset_version) ON DELETE RESTRICT,
      FOREIGN KEY (trigram_id, content_version) REFERENCES trigrams(trigram_id, content_version) ON DELETE RESTRICT,
      FOREIGN KEY (source_id, source_version) REFERENCES data_sources(source_id, source_version) ON DELETE RESTRICT
    )`,
    `CREATE TABLE six_relative_rules (
      rule_id TEXT NOT NULL,
      content_version TEXT NOT NULL,
      source_id TEXT NOT NULL,
      source_version TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('draft', 'verified')),
      ruleset_id TEXT NOT NULL,
      ruleset_version TEXT NOT NULL,
      subject_element TEXT NOT NULL,
      object_element TEXT NOT NULL,
      relative TEXT NOT NULL CHECK (relative IN ('parent', 'sibling', 'offspring', 'wealth', 'official')),
      PRIMARY KEY (rule_id, content_version),
      UNIQUE (ruleset_id, ruleset_version, subject_element, object_element),
      FOREIGN KEY (ruleset_id, ruleset_version) REFERENCES rule_versions(ruleset_id, ruleset_version) ON DELETE RESTRICT,
      FOREIGN KEY (source_id, source_version) REFERENCES data_sources(source_id, source_version) ON DELETE RESTRICT
    )`,
    `CREATE TABLE six_spirit_rules (
      rule_id TEXT NOT NULL,
      content_version TEXT NOT NULL,
      source_id TEXT NOT NULL,
      source_version TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('draft', 'verified')),
      ruleset_id TEXT NOT NULL,
      ruleset_version TEXT NOT NULL,
      day_stem_id TEXT NOT NULL,
      start_spirit_id TEXT NOT NULL,
      sequence INTEGER NOT NULL CHECK (sequence BETWEEN 1 AND 6),
      PRIMARY KEY (rule_id, content_version),
      UNIQUE (ruleset_id, ruleset_version, day_stem_id),
      FOREIGN KEY (ruleset_id, ruleset_version) REFERENCES rule_versions(ruleset_id, ruleset_version) ON DELETE RESTRICT,
      FOREIGN KEY (source_id, source_version) REFERENCES data_sources(source_id, source_version) ON DELETE RESTRICT
    )`,
    `CREATE TABLE branch_relations (
      relation_id TEXT NOT NULL,
      content_version TEXT NOT NULL,
      source_id TEXT NOT NULL,
      source_version TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('draft', 'verified')),
      ruleset_id TEXT NOT NULL,
      ruleset_version TEXT NOT NULL,
      branch_a_id TEXT NOT NULL,
      branch_b_id TEXT NOT NULL,
      relation_type TEXT NOT NULL CHECK (relation_type IN ('combine', 'clash', 'harm', 'punishment', 'break', 'generate', 'control')),
      directional INTEGER NOT NULL CHECK (directional IN (0, 1)),
      PRIMARY KEY (relation_id, content_version),
      UNIQUE (ruleset_id, ruleset_version, branch_a_id, branch_b_id, relation_type),
      FOREIGN KEY (ruleset_id, ruleset_version) REFERENCES rule_versions(ruleset_id, ruleset_version) ON DELETE RESTRICT,
      FOREIGN KEY (source_id, source_version) REFERENCES data_sources(source_id, source_version) ON DELETE RESTRICT
    )`,
    `CREATE TABLE question_categories (
      category_id TEXT NOT NULL,
      content_version TEXT NOT NULL,
      source_id TEXT NOT NULL,
      source_version TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('draft', 'verified')),
      label TEXT NOT NULL,
      description TEXT,
      PRIMARY KEY (category_id, content_version),
      FOREIGN KEY (content_version) REFERENCES content_versions(content_version) ON DELETE RESTRICT,
      FOREIGN KEY (source_id, source_version) REFERENCES data_sources(source_id, source_version) ON DELETE RESTRICT
    )`,
    `CREATE TABLE interpretation_templates (
      template_id TEXT NOT NULL,
      content_version TEXT NOT NULL,
      source_id TEXT NOT NULL,
      source_version TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('draft', 'verified')),
      category_id TEXT,
      template_key TEXT NOT NULL,
      template_text TEXT NOT NULL,
      safety_tags TEXT NOT NULL,
      PRIMARY KEY (template_id, content_version),
      UNIQUE (template_key, content_version),
      FOREIGN KEY (category_id, content_version) REFERENCES question_categories(category_id, content_version) ON DELETE RESTRICT,
      FOREIGN KEY (content_version) REFERENCES content_versions(content_version) ON DELETE RESTRICT,
      FOREIGN KEY (source_id, source_version) REFERENCES data_sources(source_id, source_version) ON DELETE RESTRICT
    )`,
    `CREATE TABLE template_variables (
      template_id TEXT NOT NULL,
      content_version TEXT NOT NULL,
      variable_name TEXT NOT NULL,
      fact_path TEXT NOT NULL,
      PRIMARY KEY (template_id, content_version, variable_name),
      FOREIGN KEY (template_id, content_version) REFERENCES interpretation_templates(template_id, content_version) ON DELETE RESTRICT
    )`,
    `CREATE TABLE rule_definitions (
      rule_id TEXT NOT NULL,
      content_version TEXT NOT NULL,
      source_id TEXT NOT NULL,
      source_version TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('draft', 'verified')),
      ruleset_id TEXT NOT NULL,
      ruleset_version TEXT NOT NULL,
      rule_type TEXT NOT NULL,
      rule_key TEXT NOT NULL,
      priority INTEGER NOT NULL,
      input_fields TEXT NOT NULL,
      output_fields TEXT NOT NULL,
      conflict_strategy TEXT NOT NULL,
      description TEXT NOT NULL,
      source_locator TEXT NOT NULL,
      PRIMARY KEY (rule_id, content_version),
      UNIQUE (ruleset_id, ruleset_version, rule_key),
      FOREIGN KEY (ruleset_id, ruleset_version) REFERENCES rule_versions(ruleset_id, ruleset_version) ON DELETE RESTRICT,
      FOREIGN KEY (source_id, source_version) REFERENCES data_sources(source_id, source_version) ON DELETE RESTRICT
    )`,
  ],
};
